// Generated by gencpp from file caros_universalrobot/UrServiceEmpty.msg
// DO NOT EDIT!


#ifndef CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEEMPTY_H
#define CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEEMPTY_H

#include <ros/service_traits.h>


#include <caros_universalrobot/UrServiceEmptyRequest.h>
#include <caros_universalrobot/UrServiceEmptyResponse.h>


namespace caros_universalrobot
{

struct UrServiceEmpty
{

typedef UrServiceEmptyRequest Request;
typedef UrServiceEmptyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UrServiceEmpty
} // namespace caros_universalrobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_universalrobot::UrServiceEmpty > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::caros_universalrobot::UrServiceEmpty&) { return value(); }
};

template<>
struct DataType< ::caros_universalrobot::UrServiceEmpty > {
  static const char* value()
  {
    return "caros_universalrobot/UrServiceEmpty";
  }

  static const char* value(const ::caros_universalrobot::UrServiceEmpty&) { return value(); }
};


// service_traits::MD5Sum< ::caros_universalrobot::UrServiceEmptyRequest> should match 
// service_traits::MD5Sum< ::caros_universalrobot::UrServiceEmpty > 
template<>
struct MD5Sum< ::caros_universalrobot::UrServiceEmptyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_universalrobot::UrServiceEmpty >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServiceEmptyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_universalrobot::UrServiceEmptyRequest> should match 
// service_traits::DataType< ::caros_universalrobot::UrServiceEmpty > 
template<>
struct DataType< ::caros_universalrobot::UrServiceEmptyRequest>
{
  static const char* value()
  {
    return DataType< ::caros_universalrobot::UrServiceEmpty >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServiceEmptyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_universalrobot::UrServiceEmptyResponse> should match 
// service_traits::MD5Sum< ::caros_universalrobot::UrServiceEmpty > 
template<>
struct MD5Sum< ::caros_universalrobot::UrServiceEmptyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_universalrobot::UrServiceEmpty >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServiceEmptyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_universalrobot::UrServiceEmptyResponse> should match 
// service_traits::DataType< ::caros_universalrobot::UrServiceEmpty > 
template<>
struct DataType< ::caros_universalrobot::UrServiceEmptyResponse>
{
  static const char* value()
  {
    return DataType< ::caros_universalrobot::UrServiceEmpty >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServiceEmptyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEEMPTY_H
