// Generated by gencpp from file caros_universalrobot/UrServicePayload.msg
// DO NOT EDIT!


#ifndef CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEPAYLOAD_H
#define CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEPAYLOAD_H

#include <ros/service_traits.h>


#include <caros_universalrobot/UrServicePayloadRequest.h>
#include <caros_universalrobot/UrServicePayloadResponse.h>


namespace caros_universalrobot
{

struct UrServicePayload
{

typedef UrServicePayloadRequest Request;
typedef UrServicePayloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UrServicePayload
} // namespace caros_universalrobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_universalrobot::UrServicePayload > {
  static const char* value()
  {
    return "b3bc68f3c25bebd79a698d60907f049f";
  }

  static const char* value(const ::caros_universalrobot::UrServicePayload&) { return value(); }
};

template<>
struct DataType< ::caros_universalrobot::UrServicePayload > {
  static const char* value()
  {
    return "caros_universalrobot/UrServicePayload";
  }

  static const char* value(const ::caros_universalrobot::UrServicePayload&) { return value(); }
};


// service_traits::MD5Sum< ::caros_universalrobot::UrServicePayloadRequest> should match 
// service_traits::MD5Sum< ::caros_universalrobot::UrServicePayload > 
template<>
struct MD5Sum< ::caros_universalrobot::UrServicePayloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_universalrobot::UrServicePayload >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServicePayloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_universalrobot::UrServicePayloadRequest> should match 
// service_traits::DataType< ::caros_universalrobot::UrServicePayload > 
template<>
struct DataType< ::caros_universalrobot::UrServicePayloadRequest>
{
  static const char* value()
  {
    return DataType< ::caros_universalrobot::UrServicePayload >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServicePayloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_universalrobot::UrServicePayloadResponse> should match 
// service_traits::MD5Sum< ::caros_universalrobot::UrServicePayload > 
template<>
struct MD5Sum< ::caros_universalrobot::UrServicePayloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_universalrobot::UrServicePayload >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServicePayloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_universalrobot::UrServicePayloadResponse> should match 
// service_traits::DataType< ::caros_universalrobot::UrServicePayload > 
template<>
struct DataType< ::caros_universalrobot::UrServicePayloadResponse>
{
  static const char* value()
  {
    return DataType< ::caros_universalrobot::UrServicePayload >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServicePayloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEPAYLOAD_H
