// Generated by gencpp from file caros_universalrobot/UrServiceForceModeUpdate.msg
// DO NOT EDIT!


#ifndef CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODEUPDATE_H
#define CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODEUPDATE_H

#include <ros/service_traits.h>


#include <caros_universalrobot/UrServiceForceModeUpdateRequest.h>
#include <caros_universalrobot/UrServiceForceModeUpdateResponse.h>


namespace caros_universalrobot
{

struct UrServiceForceModeUpdate
{

typedef UrServiceForceModeUpdateRequest Request;
typedef UrServiceForceModeUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UrServiceForceModeUpdate
} // namespace caros_universalrobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdate > {
  static const char* value()
  {
    return "30313040926e96225efb955b34d4bf7f";
  }

  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdate&) { return value(); }
};

template<>
struct DataType< ::caros_universalrobot::UrServiceForceModeUpdate > {
  static const char* value()
  {
    return "caros_universalrobot/UrServiceForceModeUpdate";
  }

  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdateRequest> should match 
// service_traits::MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdate > 
template<>
struct MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdate >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_universalrobot::UrServiceForceModeUpdateRequest> should match 
// service_traits::DataType< ::caros_universalrobot::UrServiceForceModeUpdate > 
template<>
struct DataType< ::caros_universalrobot::UrServiceForceModeUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::caros_universalrobot::UrServiceForceModeUpdate >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdateResponse> should match 
// service_traits::MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdate > 
template<>
struct MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdate >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_universalrobot::UrServiceForceModeUpdateResponse> should match 
// service_traits::DataType< ::caros_universalrobot::UrServiceForceModeUpdate > 
template<>
struct DataType< ::caros_universalrobot::UrServiceForceModeUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::caros_universalrobot::UrServiceForceModeUpdate >::value();
  }
  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODEUPDATE_H
