// Generated by gencpp from file caros_universalrobot/UrServiceForceModeUpdateRequest.msg
// DO NOT EDIT!


#ifndef CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODEUPDATEREQUEST_H
#define CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODEUPDATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Wrench.h>

namespace caros_universalrobot
{
template <class ContainerAllocator>
struct UrServiceForceModeUpdateRequest_
{
  typedef UrServiceForceModeUpdateRequest_<ContainerAllocator> Type;

  UrServiceForceModeUpdateRequest_()
    : wrench()  {
    }
  UrServiceForceModeUpdateRequest_(const ContainerAllocator& _alloc)
    : wrench(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Wrench_<ContainerAllocator>  _wrench_type;
  _wrench_type wrench;





  typedef boost::shared_ptr< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UrServiceForceModeUpdateRequest_

typedef ::caros_universalrobot::UrServiceForceModeUpdateRequest_<std::allocator<void> > UrServiceForceModeUpdateRequest;

typedef boost::shared_ptr< ::caros_universalrobot::UrServiceForceModeUpdateRequest > UrServiceForceModeUpdateRequestPtr;
typedef boost::shared_ptr< ::caros_universalrobot::UrServiceForceModeUpdateRequest const> UrServiceForceModeUpdateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caros_universalrobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'caros_common_msgs': ['/home/resps/rovi2/Rovi2/src/caros/core/caros_common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "806b3735eae05d4a43eff001f34992e5";
  }

  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x806b3735eae05d4aULL;
  static const uint64_t static_value2 = 0x43eff001f34992e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caros_universalrobot/UrServiceForceModeUpdateRequest";
  }

  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
geometry_msgs/Wrench wrench\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Wrench\n\
# This represents force in free space, separated into\n\
# its linear and angular parts.\n\
Vector3  force\n\
Vector3  torque\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wrench);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UrServiceForceModeUpdateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caros_universalrobot::UrServiceForceModeUpdateRequest_<ContainerAllocator>& v)
  {
    s << indent << "wrench: ";
    s << std::endl;
    Printer< ::geometry_msgs::Wrench_<ContainerAllocator> >::stream(s, indent + "  ", v.wrench);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODEUPDATEREQUEST_H
