// Generated by gencpp from file caros_universalrobot/UrServiceForceModeStopResponse.msg
// DO NOT EDIT!


#ifndef CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODESTOPRESPONSE_H
#define CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODESTOPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caros_universalrobot
{
template <class ContainerAllocator>
struct UrServiceForceModeStopResponse_
{
  typedef UrServiceForceModeStopResponse_<ContainerAllocator> Type;

  UrServiceForceModeStopResponse_()
    : success(false)  {
    }
  UrServiceForceModeStopResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UrServiceForceModeStopResponse_

typedef ::caros_universalrobot::UrServiceForceModeStopResponse_<std::allocator<void> > UrServiceForceModeStopResponse;

typedef boost::shared_ptr< ::caros_universalrobot::UrServiceForceModeStopResponse > UrServiceForceModeStopResponsePtr;
typedef boost::shared_ptr< ::caros_universalrobot::UrServiceForceModeStopResponse const> UrServiceForceModeStopResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caros_universalrobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'caros_common_msgs': ['/home/resps/rovi2/Rovi2/src/caros/core/caros_common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caros_universalrobot/UrServiceForceModeStopResponse";
  }

  static const char* value(const ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool success\n\
\n\
";
  }

  static const char* value(const ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UrServiceForceModeStopResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caros_universalrobot::UrServiceForceModeStopResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAROS_UNIVERSALROBOT_MESSAGE_URSERVICEFORCEMODESTOPRESPONSE_H
