// Generated by gencpp from file caros_common_msgs/ConfigInt.msg
// DO NOT EDIT!


#ifndef CAROS_COMMON_MSGS_MESSAGE_CONFIGINT_H
#define CAROS_COMMON_MSGS_MESSAGE_CONFIGINT_H

#include <ros/service_traits.h>


#include <caros_common_msgs/ConfigIntRequest.h>
#include <caros_common_msgs/ConfigIntResponse.h>


namespace caros_common_msgs
{

struct ConfigInt
{

typedef ConfigIntRequest Request;
typedef ConfigIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConfigInt
} // namespace caros_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_common_msgs::ConfigInt > {
  static const char* value()
  {
    return "90cf831f17d9eb3982e6a04cd41f654b";
  }

  static const char* value(const ::caros_common_msgs::ConfigInt&) { return value(); }
};

template<>
struct DataType< ::caros_common_msgs::ConfigInt > {
  static const char* value()
  {
    return "caros_common_msgs/ConfigInt";
  }

  static const char* value(const ::caros_common_msgs::ConfigInt&) { return value(); }
};


// service_traits::MD5Sum< ::caros_common_msgs::ConfigIntRequest> should match 
// service_traits::MD5Sum< ::caros_common_msgs::ConfigInt > 
template<>
struct MD5Sum< ::caros_common_msgs::ConfigIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_common_msgs::ConfigInt >::value();
  }
  static const char* value(const ::caros_common_msgs::ConfigIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_common_msgs::ConfigIntRequest> should match 
// service_traits::DataType< ::caros_common_msgs::ConfigInt > 
template<>
struct DataType< ::caros_common_msgs::ConfigIntRequest>
{
  static const char* value()
  {
    return DataType< ::caros_common_msgs::ConfigInt >::value();
  }
  static const char* value(const ::caros_common_msgs::ConfigIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_common_msgs::ConfigIntResponse> should match 
// service_traits::MD5Sum< ::caros_common_msgs::ConfigInt > 
template<>
struct MD5Sum< ::caros_common_msgs::ConfigIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_common_msgs::ConfigInt >::value();
  }
  static const char* value(const ::caros_common_msgs::ConfigIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_common_msgs::ConfigIntResponse> should match 
// service_traits::DataType< ::caros_common_msgs::ConfigInt > 
template<>
struct DataType< ::caros_common_msgs::ConfigIntResponse>
{
  static const char* value()
  {
    return DataType< ::caros_common_msgs::ConfigInt >::value();
  }
  static const char* value(const ::caros_common_msgs::ConfigIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_COMMON_MSGS_MESSAGE_CONFIGINT_H
