// Generated by gencpp from file caros_common_msgs/ConfigIntRequest.msg
// DO NOT EDIT!


#ifndef CAROS_COMMON_MSGS_MESSAGE_CONFIGINTREQUEST_H
#define CAROS_COMMON_MSGS_MESSAGE_CONFIGINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caros_common_msgs
{
template <class ContainerAllocator>
struct ConfigIntRequest_
{
  typedef ConfigIntRequest_<ContainerAllocator> Type;

  ConfigIntRequest_()
    : value(0)  {
    }
  ConfigIntRequest_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigIntRequest_

typedef ::caros_common_msgs::ConfigIntRequest_<std::allocator<void> > ConfigIntRequest;

typedef boost::shared_ptr< ::caros_common_msgs::ConfigIntRequest > ConfigIntRequestPtr;
typedef boost::shared_ptr< ::caros_common_msgs::ConfigIntRequest const> ConfigIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caros_common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'caros_common_msgs': ['/home/resps/rovi2/Rovi2/src/caros/core/caros_common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9d213e8c146065ec958333c617eb1a6";
  }

  static const char* value(const ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9d213e8c146065eULL;
  static const uint64_t static_value2 = 0xc958333c617eb1a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caros_common_msgs/ConfigIntRequest";
  }

  static const char* value(const ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint32 value\n\
";
  }

  static const char* value(const ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caros_common_msgs::ConfigIntRequest_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAROS_COMMON_MSGS_MESSAGE_CONFIGINTREQUEST_H
