// Generated by gencpp from file caros_common_msgs/ConfigBoolRequest.msg
// DO NOT EDIT!


#ifndef CAROS_COMMON_MSGS_MESSAGE_CONFIGBOOLREQUEST_H
#define CAROS_COMMON_MSGS_MESSAGE_CONFIGBOOLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace caros_common_msgs
{
template <class ContainerAllocator>
struct ConfigBoolRequest_
{
  typedef ConfigBoolRequest_<ContainerAllocator> Type;

  ConfigBoolRequest_()
    : value(false)  {
    }
  ConfigBoolRequest_(const ContainerAllocator& _alloc)
    : value(false)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigBoolRequest_

typedef ::caros_common_msgs::ConfigBoolRequest_<std::allocator<void> > ConfigBoolRequest;

typedef boost::shared_ptr< ::caros_common_msgs::ConfigBoolRequest > ConfigBoolRequestPtr;
typedef boost::shared_ptr< ::caros_common_msgs::ConfigBoolRequest const> ConfigBoolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caros_common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'caros_common_msgs': ['/home/resps/rovi2/Rovi2/src/caros/core/caros_common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e431d687bf4b2c65fbd94b12ae0cb5d9";
  }

  static const char* value(const ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe431d687bf4b2c65ULL;
  static const uint64_t static_value2 = 0xfbd94b12ae0cb5d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caros_common_msgs/ConfigBoolRequest";
  }

  static const char* value(const ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool value\n\
";
  }

  static const char* value(const ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigBoolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caros_common_msgs::ConfigBoolRequest_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAROS_COMMON_MSGS_MESSAGE_CONFIGBOOLREQUEST_H
