// Generated by gencpp from file caros_common_msgs/ConfigBool.msg
// DO NOT EDIT!


#ifndef CAROS_COMMON_MSGS_MESSAGE_CONFIGBOOL_H
#define CAROS_COMMON_MSGS_MESSAGE_CONFIGBOOL_H

#include <ros/service_traits.h>


#include <caros_common_msgs/ConfigBoolRequest.h>
#include <caros_common_msgs/ConfigBoolResponse.h>


namespace caros_common_msgs
{

struct ConfigBool
{

typedef ConfigBoolRequest Request;
typedef ConfigBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConfigBool
} // namespace caros_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_common_msgs::ConfigBool > {
  static const char* value()
  {
    return "24a0f9fd764459b7e35d04a0dd83dd11";
  }

  static const char* value(const ::caros_common_msgs::ConfigBool&) { return value(); }
};

template<>
struct DataType< ::caros_common_msgs::ConfigBool > {
  static const char* value()
  {
    return "caros_common_msgs/ConfigBool";
  }

  static const char* value(const ::caros_common_msgs::ConfigBool&) { return value(); }
};


// service_traits::MD5Sum< ::caros_common_msgs::ConfigBoolRequest> should match 
// service_traits::MD5Sum< ::caros_common_msgs::ConfigBool > 
template<>
struct MD5Sum< ::caros_common_msgs::ConfigBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_common_msgs::ConfigBool >::value();
  }
  static const char* value(const ::caros_common_msgs::ConfigBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_common_msgs::ConfigBoolRequest> should match 
// service_traits::DataType< ::caros_common_msgs::ConfigBool > 
template<>
struct DataType< ::caros_common_msgs::ConfigBoolRequest>
{
  static const char* value()
  {
    return DataType< ::caros_common_msgs::ConfigBool >::value();
  }
  static const char* value(const ::caros_common_msgs::ConfigBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_common_msgs::ConfigBoolResponse> should match 
// service_traits::MD5Sum< ::caros_common_msgs::ConfigBool > 
template<>
struct MD5Sum< ::caros_common_msgs::ConfigBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_common_msgs::ConfigBool >::value();
  }
  static const char* value(const ::caros_common_msgs::ConfigBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_common_msgs::ConfigBoolResponse> should match 
// service_traits::DataType< ::caros_common_msgs::ConfigBool > 
template<>
struct DataType< ::caros_common_msgs::ConfigBoolResponse>
{
  static const char* value()
  {
    return DataType< ::caros_common_msgs::ConfigBool >::value();
  }
  static const char* value(const ::caros_common_msgs::ConfigBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_COMMON_MSGS_MESSAGE_CONFIGBOOL_H
