// Generated by gencpp from file caros_common_msgs/EmptySrv.msg
// DO NOT EDIT!


#ifndef CAROS_COMMON_MSGS_MESSAGE_EMPTYSRV_H
#define CAROS_COMMON_MSGS_MESSAGE_EMPTYSRV_H

#include <ros/service_traits.h>


#include <caros_common_msgs/EmptySrvRequest.h>
#include <caros_common_msgs/EmptySrvResponse.h>


namespace caros_common_msgs
{

struct EmptySrv
{

typedef EmptySrvRequest Request;
typedef EmptySrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmptySrv
} // namespace caros_common_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_common_msgs::EmptySrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::caros_common_msgs::EmptySrv&) { return value(); }
};

template<>
struct DataType< ::caros_common_msgs::EmptySrv > {
  static const char* value()
  {
    return "caros_common_msgs/EmptySrv";
  }

  static const char* value(const ::caros_common_msgs::EmptySrv&) { return value(); }
};


// service_traits::MD5Sum< ::caros_common_msgs::EmptySrvRequest> should match 
// service_traits::MD5Sum< ::caros_common_msgs::EmptySrv > 
template<>
struct MD5Sum< ::caros_common_msgs::EmptySrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_common_msgs::EmptySrv >::value();
  }
  static const char* value(const ::caros_common_msgs::EmptySrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_common_msgs::EmptySrvRequest> should match 
// service_traits::DataType< ::caros_common_msgs::EmptySrv > 
template<>
struct DataType< ::caros_common_msgs::EmptySrvRequest>
{
  static const char* value()
  {
    return DataType< ::caros_common_msgs::EmptySrv >::value();
  }
  static const char* value(const ::caros_common_msgs::EmptySrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_common_msgs::EmptySrvResponse> should match 
// service_traits::MD5Sum< ::caros_common_msgs::EmptySrv > 
template<>
struct MD5Sum< ::caros_common_msgs::EmptySrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_common_msgs::EmptySrv >::value();
  }
  static const char* value(const ::caros_common_msgs::EmptySrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_common_msgs::EmptySrvResponse> should match 
// service_traits::DataType< ::caros_common_msgs::EmptySrv > 
template<>
struct DataType< ::caros_common_msgs::EmptySrvResponse>
{
  static const char* value()
  {
    return DataType< ::caros_common_msgs::EmptySrv >::value();
  }
  static const char* value(const ::caros_common_msgs::EmptySrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_COMMON_MSGS_MESSAGE_EMPTYSRV_H
