// Generated by gencpp from file caros_control_msgs/SerialDeviceMoveVelQ.msg
// DO NOT EDIT!


#ifndef CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVEVELQ_H
#define CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVEVELQ_H

#include <ros/service_traits.h>


#include <caros_control_msgs/SerialDeviceMoveVelQRequest.h>
#include <caros_control_msgs/SerialDeviceMoveVelQResponse.h>


namespace caros_control_msgs
{

struct SerialDeviceMoveVelQ
{

typedef SerialDeviceMoveVelQRequest Request;
typedef SerialDeviceMoveVelQResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialDeviceMoveVelQ
} // namespace caros_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQ > {
  static const char* value()
  {
    return "e405cc67ad2f49de8c759f388d4bac88";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMoveVelQ&) { return value(); }
};

template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveVelQ > {
  static const char* value()
  {
    return "caros_control_msgs/SerialDeviceMoveVelQ";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMoveVelQ&) { return value(); }
};


// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQRequest> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQ > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQ >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveVelQRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveVelQRequest> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveVelQ > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveVelQRequest>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceMoveVelQ >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveVelQRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQResponse> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQ > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceMoveVelQ >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveVelQResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveVelQResponse> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveVelQ > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveVelQResponse>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceMoveVelQ >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveVelQResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVEVELQ_H
