// Generated by gencpp from file caros_control_msgs/SerialDeviceMovePtpRequest.msg
// DO NOT EDIT!


#ifndef CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVEPTPREQUEST_H
#define CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVEPTPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <caros_common_msgs/Q.h>

namespace caros_control_msgs
{
template <class ContainerAllocator>
struct SerialDeviceMovePtpRequest_
{
  typedef SerialDeviceMovePtpRequest_<ContainerAllocator> Type;

  SerialDeviceMovePtpRequest_()
    : targets()
    , speeds()
    , blends()  {
    }
  SerialDeviceMovePtpRequest_(const ContainerAllocator& _alloc)
    : targets(_alloc)
    , speeds(_alloc)
    , blends(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::caros_common_msgs::Q_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::caros_common_msgs::Q_<ContainerAllocator> >::other >  _targets_type;
  _targets_type targets;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _speeds_type;
  _speeds_type speeds;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _blends_type;
  _blends_type blends;





  typedef boost::shared_ptr< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SerialDeviceMovePtpRequest_

typedef ::caros_control_msgs::SerialDeviceMovePtpRequest_<std::allocator<void> > SerialDeviceMovePtpRequest;

typedef boost::shared_ptr< ::caros_control_msgs::SerialDeviceMovePtpRequest > SerialDeviceMovePtpRequestPtr;
typedef boost::shared_ptr< ::caros_control_msgs::SerialDeviceMovePtpRequest const> SerialDeviceMovePtpRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caros_control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'caros_common_msgs': ['/home/resps/rovi2/Rovi2/src/caros/core/caros_common_msgs/msg'], 'caros_control_msgs': ['/home/resps/rovi2/Rovi2/src/caros/interfaces/caros_control_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f41d7c80d23e8e22f8652e0e8fa76712";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf41d7c80d23e8e22ULL;
  static const uint64_t static_value2 = 0xf8652e0e8fa76712ULL;
};

template<class ContainerAllocator>
struct DataType< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caros_control_msgs/SerialDeviceMovePtpRequest";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
caros_common_msgs/Q[] targets\n\
\n\
\n\
float32[] speeds\n\
\n\
\n\
float32[] blends\n\
\n\
\n\
================================================================================\n\
MSG: caros_common_msgs/Q\n\
# A configuration Q\n\
float64[] data\n\
";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targets);
      stream.next(m.speeds);
      stream.next(m.blends);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialDeviceMovePtpRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caros_control_msgs::SerialDeviceMovePtpRequest_<ContainerAllocator>& v)
  {
    s << indent << "targets[]" << std::endl;
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      s << indent << "  targets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::caros_common_msgs::Q_<ContainerAllocator> >::stream(s, indent + "    ", v.targets[i]);
    }
    s << indent << "speeds[]" << std::endl;
    for (size_t i = 0; i < v.speeds.size(); ++i)
    {
      s << indent << "  speeds[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.speeds[i]);
    }
    s << indent << "blends[]" << std::endl;
    for (size_t i = 0; i < v.blends.size(); ++i)
    {
      s << indent << "  blends[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.blends[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVEPTPREQUEST_H
