// Generated by gencpp from file caros_control_msgs/SerialDeviceForceControlStop.msg
// DO NOT EDIT!


#ifndef CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEFORCECONTROLSTOP_H
#define CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEFORCECONTROLSTOP_H

#include <ros/service_traits.h>


#include <caros_control_msgs/SerialDeviceForceControlStopRequest.h>
#include <caros_control_msgs/SerialDeviceForceControlStopResponse.h>


namespace caros_control_msgs
{

struct SerialDeviceForceControlStop
{

typedef SerialDeviceForceControlStopRequest Request;
typedef SerialDeviceForceControlStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialDeviceForceControlStop
} // namespace caros_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStop > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlStop&) { return value(); }
};

template<>
struct DataType< ::caros_control_msgs::SerialDeviceForceControlStop > {
  static const char* value()
  {
    return "caros_control_msgs/SerialDeviceForceControlStop";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlStop&) { return value(); }
};


// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStopRequest> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStop > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStop >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceForceControlStopRequest> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceForceControlStop > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceForceControlStopRequest>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceForceControlStop >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStopResponse> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStop > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceForceControlStop >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceForceControlStopResponse> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceForceControlStop > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceForceControlStopResponse>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceForceControlStop >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEFORCECONTROLSTOP_H
