// Generated by gencpp from file caros_control_msgs/SerialDeviceForceControlUpdate.msg
// DO NOT EDIT!


#ifndef CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEFORCECONTROLUPDATE_H
#define CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEFORCECONTROLUPDATE_H

#include <ros/service_traits.h>


#include <caros_control_msgs/SerialDeviceForceControlUpdateRequest.h>
#include <caros_control_msgs/SerialDeviceForceControlUpdateResponse.h>


namespace caros_control_msgs
{

struct SerialDeviceForceControlUpdate
{

typedef SerialDeviceForceControlUpdateRequest Request;
typedef SerialDeviceForceControlUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialDeviceForceControlUpdate
} // namespace caros_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdate > {
  static const char* value()
  {
    return "30313040926e96225efb955b34d4bf7f";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlUpdate&) { return value(); }
};

template<>
struct DataType< ::caros_control_msgs::SerialDeviceForceControlUpdate > {
  static const char* value()
  {
    return "caros_control_msgs/SerialDeviceForceControlUpdate";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdateRequest> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdate > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdate >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceForceControlUpdateRequest> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceForceControlUpdate > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceForceControlUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceForceControlUpdate >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdateResponse> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdate > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceForceControlUpdate >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceForceControlUpdateResponse> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceForceControlUpdate > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceForceControlUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceForceControlUpdate >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceForceControlUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEFORCECONTROLUPDATE_H
