// Generated by gencpp from file caros_control_msgs/SerialDeviceMoveServoQ.msg
// DO NOT EDIT!


#ifndef CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVESERVOQ_H
#define CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVESERVOQ_H

#include <ros/service_traits.h>


#include <caros_control_msgs/SerialDeviceMoveServoQRequest.h>
#include <caros_control_msgs/SerialDeviceMoveServoQResponse.h>


namespace caros_control_msgs
{

struct SerialDeviceMoveServoQ
{

typedef SerialDeviceMoveServoQRequest Request;
typedef SerialDeviceMoveServoQResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialDeviceMoveServoQ
} // namespace caros_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQ > {
  static const char* value()
  {
    return "8289fdc0949acdbc17fb0989cb66f411";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoQ&) { return value(); }
};

template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveServoQ > {
  static const char* value()
  {
    return "caros_control_msgs/SerialDeviceMoveServoQ";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoQ&) { return value(); }
};


// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQRequest> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQ > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQ >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoQRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveServoQRequest> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveServoQ > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveServoQRequest>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceMoveServoQ >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoQRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQResponse> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQ > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoQ >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoQResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveServoQResponse> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveServoQ > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveServoQResponse>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceMoveServoQ >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoQResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVESERVOQ_H
