// Generated by gencpp from file caros_control_msgs/SerialDeviceMoveServoT.msg
// DO NOT EDIT!


#ifndef CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVESERVOT_H
#define CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVESERVOT_H

#include <ros/service_traits.h>


#include <caros_control_msgs/SerialDeviceMoveServoTRequest.h>
#include <caros_control_msgs/SerialDeviceMoveServoTResponse.h>


namespace caros_control_msgs
{

struct SerialDeviceMoveServoT
{

typedef SerialDeviceMoveServoTRequest Request;
typedef SerialDeviceMoveServoTResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialDeviceMoveServoT
} // namespace caros_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoT > {
  static const char* value()
  {
    return "0092a8e71a6ac28671c6e239deeca080";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoT&) { return value(); }
};

template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveServoT > {
  static const char* value()
  {
    return "caros_control_msgs/SerialDeviceMoveServoT";
  }

  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoT&) { return value(); }
};


// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoTRequest> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoT > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoTRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoT >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoTRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveServoTRequest> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveServoT > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveServoTRequest>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceMoveServoT >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoTRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoTResponse> should match 
// service_traits::MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoT > 
template<>
struct MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoTResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_control_msgs::SerialDeviceMoveServoT >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoTResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveServoTResponse> should match 
// service_traits::DataType< ::caros_control_msgs::SerialDeviceMoveServoT > 
template<>
struct DataType< ::caros_control_msgs::SerialDeviceMoveServoTResponse>
{
  static const char* value()
  {
    return DataType< ::caros_control_msgs::SerialDeviceMoveServoT >::value();
  }
  static const char* value(const ::caros_control_msgs::SerialDeviceMoveServoTResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_CONTROL_MSGS_MESSAGE_SERIALDEVICEMOVESERVOT_H
