// Generated by gencpp from file caros_common_robwork_msgs/GetRwState.msg
// DO NOT EDIT!


#ifndef CAROS_COMMON_ROBWORK_MSGS_MESSAGE_GETRWSTATE_H
#define CAROS_COMMON_ROBWORK_MSGS_MESSAGE_GETRWSTATE_H

#include <ros/service_traits.h>


#include <caros_common_robwork_msgs/GetRwStateRequest.h>
#include <caros_common_robwork_msgs/GetRwStateResponse.h>


namespace caros_common_robwork_msgs
{

struct GetRwState
{

typedef GetRwStateRequest Request;
typedef GetRwStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRwState
} // namespace caros_common_robwork_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::caros_common_robwork_msgs::GetRwState > {
  static const char* value()
  {
    return "ec5f59bcd9871c158266b6d4f91ec6c6";
  }

  static const char* value(const ::caros_common_robwork_msgs::GetRwState&) { return value(); }
};

template<>
struct DataType< ::caros_common_robwork_msgs::GetRwState > {
  static const char* value()
  {
    return "caros_common_robwork_msgs/GetRwState";
  }

  static const char* value(const ::caros_common_robwork_msgs::GetRwState&) { return value(); }
};


// service_traits::MD5Sum< ::caros_common_robwork_msgs::GetRwStateRequest> should match 
// service_traits::MD5Sum< ::caros_common_robwork_msgs::GetRwState > 
template<>
struct MD5Sum< ::caros_common_robwork_msgs::GetRwStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::caros_common_robwork_msgs::GetRwState >::value();
  }
  static const char* value(const ::caros_common_robwork_msgs::GetRwStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_common_robwork_msgs::GetRwStateRequest> should match 
// service_traits::DataType< ::caros_common_robwork_msgs::GetRwState > 
template<>
struct DataType< ::caros_common_robwork_msgs::GetRwStateRequest>
{
  static const char* value()
  {
    return DataType< ::caros_common_robwork_msgs::GetRwState >::value();
  }
  static const char* value(const ::caros_common_robwork_msgs::GetRwStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::caros_common_robwork_msgs::GetRwStateResponse> should match 
// service_traits::MD5Sum< ::caros_common_robwork_msgs::GetRwState > 
template<>
struct MD5Sum< ::caros_common_robwork_msgs::GetRwStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::caros_common_robwork_msgs::GetRwState >::value();
  }
  static const char* value(const ::caros_common_robwork_msgs::GetRwStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::caros_common_robwork_msgs::GetRwStateResponse> should match 
// service_traits::DataType< ::caros_common_robwork_msgs::GetRwState > 
template<>
struct DataType< ::caros_common_robwork_msgs::GetRwStateResponse>
{
  static const char* value()
  {
    return DataType< ::caros_common_robwork_msgs::GetRwState >::value();
  }
  static const char* value(const ::caros_common_robwork_msgs::GetRwStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAROS_COMMON_ROBWORK_MSGS_MESSAGE_GETRWSTATE_H
