// Generated by gencpp from file caros_common_robwork_msgs/RwState.msg
// DO NOT EDIT!


#ifndef CAROS_COMMON_ROBWORK_MSGS_MESSAGE_RWSTATE_H
#define CAROS_COMMON_ROBWORK_MSGS_MESSAGE_RWSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <caros_common_robwork_msgs/RwStateData.h>

namespace caros_common_robwork_msgs
{
template <class ContainerAllocator>
struct RwState_
{
  typedef RwState_<ContainerAllocator> Type;

  RwState_()
    : state_data()  {
    }
  RwState_(const ContainerAllocator& _alloc)
    : state_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::caros_common_robwork_msgs::RwStateData_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::caros_common_robwork_msgs::RwStateData_<ContainerAllocator> >::other >  _state_data_type;
  _state_data_type state_data;





  typedef boost::shared_ptr< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> const> ConstPtr;

}; // struct RwState_

typedef ::caros_common_robwork_msgs::RwState_<std::allocator<void> > RwState;

typedef boost::shared_ptr< ::caros_common_robwork_msgs::RwState > RwStatePtr;
typedef boost::shared_ptr< ::caros_common_robwork_msgs::RwState const> RwStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::caros_common_robwork_msgs::RwState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace caros_common_robwork_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'caros_common_robwork_msgs': ['/home/resps/rovi2/Rovi2/src/caros/core/caros_common_robwork_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91a8153d2e6cb16c0e4126365820f1d3";
  }

  static const char* value(const ::caros_common_robwork_msgs::RwState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91a8153d2e6cb16cULL;
  static const uint64_t static_value2 = 0x0e4126365820f1d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "caros_common_robwork_msgs/RwState";
  }

  static const char* value(const ::caros_common_robwork_msgs::RwState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Serialization of RobWork state\n\
caros_common_robwork_msgs/RwStateData[] state_data\n\
\n\
================================================================================\n\
MSG: caros_common_robwork_msgs/RwStateData\n\
# Serialization of RobWork state data\n\
string name\n\
uint32 size\n\
uint8[] data\n\
";
  }

  static const char* value(const ::caros_common_robwork_msgs::RwState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RwState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::caros_common_robwork_msgs::RwState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::caros_common_robwork_msgs::RwState_<ContainerAllocator>& v)
  {
    s << indent << "state_data[]" << std::endl;
    for (size_t i = 0; i < v.state_data.size(); ++i)
    {
      s << indent << "  state_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::caros_common_robwork_msgs::RwStateData_<ContainerAllocator> >::stream(s, indent + "    ", v.state_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAROS_COMMON_ROBWORK_MSGS_MESSAGE_RWSTATE_H
